# Site settings
title: Just for Fun!
email: your-email@domain.com


description: > # this means to ignore newlines until "baseurl:"The blog is just built in the last few days, so it needs improving further!
  
baseurl: "" # the subpath of your site, e.g. /blog/


url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
